from main.service.pre_explanation.center_concepts import CenterMostConceptsService
from main.service.pre_explanation.most_popular_concepts import MostPopularConcepts

CENTER_MOST_CONCEPTS = CenterMostConceptsService().center_most_concepts
MOST_POPULAR_CONCEPTS = MostPopularConcepts().image_most_popular_concepts
